# Generated by Django 4.1.2 on 2022-10-20 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag', models.BooleanField(default=False)),
                ('date_time_pci', models.CharField(default='No', max_length=150)),
                ('date_time_package', models.CharField(default='No', max_length=150)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial_num', models.CharField(max_length=14)),
                ('message', models.CharField(max_length=255)),
                ('date_time', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand', models.CharField(max_length=150)),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'statistic',
            },
        ),
        migrations.CreateModel(
            name='SerialNumRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num_router', models.CharField(max_length=14, unique=True)),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.devices')),
            ],
            options={
                'db_table': 'serial_num_router',
            },
        ),
        migrations.CreateModel(
            name='SerialNumPKI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num_pki', models.CharField(max_length=14, unique=True)),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.devices')),
            ],
            options={
                'db_table': 'serial_num_pki',
            },
        ),
        migrations.CreateModel(
            name='SerialNumPCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num_pcb', models.CharField(max_length=14, unique=True)),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.devices')),
            ],
            options={
                'db_table': 'serial_num_pcb',
            },
        ),
        migrations.CreateModel(
            name='SerialNumPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num_package', models.CharField(max_length=14, unique=True)),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.devices')),
            ],
            options={
                'db_table': 'serial_num_package',
            },
        ),
        migrations.CreateModel(
            name='SerialNumCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num_case', models.CharField(max_length=14, unique=True)),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.devices')),
            ],
            options={
                'db_table': 'serial_num_case',
            },
        ),
        migrations.CreateModel(
            name='SerialNumBP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num_BP', models.CharField(max_length=14, unique=True)),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.devices')),
            ],
            options={
                'db_table': 'serial_num_BP',
            },
        ),
        migrations.CreateModel(
            name='SerialNumBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num_board', models.CharField(max_length=14, unique=True)),
                ('visual_inspection', models.BooleanField(default=None)),
                ('visual_inspection_error_code', models.CharField(default=None, max_length=3)),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.devices')),
            ],
            options={
                'db_table': 'serial_num_board',
            },
        ),
        migrations.CreateModel(
            name='Macs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=14, unique=True)),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.devices')),
            ],
            options={
                'db_table': 'macs',
            },
        ),
        migrations.AddField(
            model_name='devices',
            name='eth1addr_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mac2', to='stands.macs'),
        ),
        migrations.AddField(
            model_name='devices',
            name='eth2addr_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mac3', to='stands.macs'),
        ),
        migrations.AddField(
            model_name='devices',
            name='ethaddr_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mac1', to='stands.macs'),
        ),
        migrations.AddField(
            model_name='devices',
            name='serial_num_board_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.serialnumboard'),
        ),
        migrations.AddField(
            model_name='devices',
            name='serial_num_bp_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.serialnumbp'),
        ),
        migrations.AddField(
            model_name='devices',
            name='serial_num_case_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.serialnumcase'),
        ),
        migrations.AddField(
            model_name='devices',
            name='serial_num_package_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.serialnumpackage'),
        ),
        migrations.AddField(
            model_name='devices',
            name='serial_num_pcb_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.serialnumpcb'),
        ),
        migrations.AddField(
            model_name='devices',
            name='serial_num_pki_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.serialnumpki'),
        ),
        migrations.AddField(
            model_name='devices',
            name='serial_num_router_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.serialnumrouter'),
        ),
    ]
