# Generated by Django 4.1.2 on 2022-10-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0002_detailtype_devicetype_placeofproduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='manufacturer',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
