# Generated by Django 4.1.2 on 2022-11-01 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0003_alter_statistic_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='eth1addr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mac2', to='stands.macs', unique=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='eth2addr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mac3', to='stands.macs', unique=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='ethaddr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mac1', to='stands.macs', unique=True),
        ),
        migrations.AlterField(
            model_name='macs',
            name='device_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.devices', unique=True),
        ),
        migrations.AlterField(
            model_name='serialnumboard',
            name='device_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.devices'),
        ),
        migrations.AlterField(
            model_name='serialnumboard',
            name='visual_inspection_author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='serialnumboard',
            name='visual_inspection_error_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='serialnumbp',
            name='device_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.devices'),
        ),
        migrations.AlterField(
            model_name='serialnumcase',
            name='device_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.devices'),
        ),
        migrations.AlterField(
            model_name='serialnumpackage',
            name='device_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.devices'),
        ),
        migrations.AlterField(
            model_name='serialnumpcb',
            name='device_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.devices'),
        ),
        migrations.AlterField(
            model_name='serialnumpki',
            name='device_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.devices'),
        ),
    ]
